# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73b07a3569b092b9a911663006c8bf398d0768dd58fa01443b7bac36dc2d311eb58f88ef6f4274886a246ec2aaa80f2e4ba1711ec3a5e62a685fbb2ef774365

test:
  secret_key_base: 242075d447bc098971e65c9e03151753e117313e8d6bfdc79217f978636ac5684e5c7cc7db6190cd365738e151ce4bebcfb3e42bb1089409273a03bdead91e5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
